[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = ["pip install --user --upgrade pip", "pip install --user -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd lp && python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120" 