[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --break-system-packages --upgrade pip", "pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd lp && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120" 